inputs:
  os:
    description: 'linux, windows or mac'
    required: true
  extension:
    description: 'tar.gz, exe, zip, sit or dmg'
    required: true
  artifacts_dir:
    description: 'IDE artifacts output directory'
    required: true
runs:
  using: composite
  steps:
    - name: Upload .${{inputs.extension}}
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{inputs.os}}-${{inputs.extension}}
        if-no-files-found: 'error'
        retention-days: 1
        path: |
          ${{inputs.artifacts_dir}}/*.${{inputs.extension}}