inputs:
  os:
    description: 'linux, windows or mac'
    required: true
  extension:
    description: 'tar.gz, exe, zip, sit or dmg'
    required: true
  artifacts_dir:
    description: 'IDE artifacts output directory'
    required: true
env:
  R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
runs:
  using: composite
  steps:
    - name: Upload .${{inputs.extension}}
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{inputs.os}}-${{inputs.extension}}
        if-no-files-found: 'error'
        retention-days: 1
        path: |
          ${{inputs.artifacts_dir}}/*.${{inputs.extension}}
    - name: Prepare for publishing
      shell: bash
      # language=bash
      run: |
        mkdir -p ${{inputs.artifacts_dir}}/publish
        cd ${{inputs.artifacts_dir}}
        for file in *.${{inputs.extension}}; do mv "$file" "publish";done
    - name: Publish .${{inputs.extension}} to R2
      uses: ryand56/r2-upload-action@latest
      with:
        r2-account-id: $R2_ACCOUNT_ID
        r2-access-key-id: $R2_ACCESS_KEY_ID
        r2-secret-access-key: $R2_SECRET_ACCESS_KEY
        r2-bucket: desktop-distro
        source-dir: ${{inputs.artifacts_dir}}/publish/
        destination-dir: ./code/
